name: emulsion
title: Emulsion
version: '0.9.37'
summary: Better gaming throught chemistry
description: |
  Emulsion scans local game directories, normalizes metadata, and exposes a structured interface for launching titles. It manages emulator installation based on the user’s selected platforms.
  and provides a beautiful interface to launch your favorite games.
website: https://yphil.gitlab.io/emulsion/
source-code: https://gitlab.com/yphil/emulsion
issues: https://gitlab.com/yphil/emulsion/-/issues
license: GPL-3.0+
donation: https://yphil.gitlab.io/ext/support.html
contact:
  - xaccrocheur@gmail.com
  - https://yphil.gitlab.io/
grade: stable
confinement: classic
base: core22
icon: settings.svg

apps:
  emulsion:
    command: bin/emulsion
    desktop: usr/share/applications/io.gitlab.yphil.emulsion.desktop

parts:
  emulsion:
    plugin: dump
    source: https://github.com/yPhil-gh/Emulsion/releases/download/0.9.37/linux-unpacked.tar.gz
    source-checksum: sha256/c290dd687d20f62a833e965f2fe9cf7ba30777e51388486e8b356a0c0bf4c737
    organize:
      '*': usr/lib/emulsion/
    stage:
      - usr/lib/emulsion/
    prime:
      - usr/lib/emulsion/

  local-files:
    source: .
    source-type: local
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp local/emulsion-wrapper $SNAPCRAFT_PART_INSTALL/bin/emulsion
      cp local/io.gitlab.yphil.emulsion.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
    prime:
      - bin/emulsion
      - usr/share/applications/io.gitlab.yphil.emulsion.desktop
